import "bootstrap";
import Chartkick from "chartkick";
window.Chartkick = Chartkick;
import Highcharts from "highcharts";
Chartkick.addAdapter(Highcharts);
import "onepagescroll";
import "navbar";
import "output";
import "filter";
import {dashboard} from "dashboardtabs";
import {dashboardtab} from "dashboardtabs";
dashboard();
dashboardtab();
import "animations";
import {activeTabSelector} from "navbar";
